config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  get 'companies/edit' #Don't know why I had to put this in
  get 'companies/destroy' #Don't know why I had to put this in
  get 'companies/show' #Don't know why I had to put this in

  resources :companies, :contacts, :friendships

  root 'home#index'

end

app/models/company.rb
class Company < ActiveRecord::Base

  # Relationships
  has_many :contacts, :dependent => :destroy

  # Validations
  validates_presence_of :name
  validates_length_of :name, :maximum => 50
  validates_uniqueness_of :name

  # CarrierWave
  mount_uploader :image, ImageUploader
end

app/models/contact.rb
class Contact < ActiveRecord::Base

  # Relationships
  belongs_to :company
  has_many :friendships, :dependent => :destroy
  has_many :friends, :through => :friendships, :dependent => :destroy
  has_many :inverse_friendships, :class_name => 'Friendship', :foreign_key => 'friend_id', :dependent => :destroy
  has_many :inverse_friends, :through => :inverse_friendships, :source => :contact, :dependent => :destroy

  # Validations
  EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i

  validates_presence_of :first_name, :last_name, :company, :position
  validates_length_of :first_name, :last_name, :position, :maximum => 50
  validates_format_of :email, :with => EMAIL_REGEX, :allow_blank => true
  validates_numericality_of :phone, :allow_blank => true

  # CarrierWave
  mount_uploader :image, ImageUploader

  # Custom Methods
  def full_name
    self.first_name + ' ' + self.last_name
  end

  def friendships_build
    Friendship.where(:contact => self) + Friendship.where(:friend => self)
  end
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base

  # Relationships
  belongs_to :contact
  belongs_to :friend, :class_name => 'Contact'

  # Validations
  validate :uniqueness_of_combination
  validate :cannot_be_friends_with_self # Validate that contact and friend arent the same

  # Custom Methods
  def uniqueness_of_combination

    attempted_friendship = [contact_id, friend_id]

    Friendship.all.each do |f|
      inverse_friendship = [f.friend.id, f.contact.id]
      if attempted_friendship == inverse_friendship || attempted_friendship == [f.contact_id, f.friend_id]
        errors.add(:users_id,'. Friendship already exists')
      end
    end
  end

  def cannot_be_friends_with_self
    if contact_id == friend_id
      errors.add(:user_id, '. Sorry, One cannot be friends with oneself')
    end
  end

  def friendship_desc
    self.contact.full_name + ' is friends with ' + self.friend.full_name
  end

  def friendship_short_desc
    self.contact.first_name + ' with ' + self.friend.first_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  def index
    @companies = Company.all
  end

  def show
    @company = Company.find(params[:id])
    @contacts = Contact.where(company_id: params[:id])
  end

  def create
    @company = Company.new(company_params)

    if @company.save
      flash[:notice] = "Company '#{@company.name}' created Successfully"
      redirect_to(:controller => 'home', :action => 'index')

    else
      render('new')
    end
  end

  def edit
    @company = Company.find(params[:id])
  end

  def new
    @company = Company.new
  end

  def update
    @company = Company.find(params[:id])

    if @company.update_attributes(company_params)
      flash[:notice] = "Company '#{@company.name}' has been updated"
      redirect_to(:action => 'show', :id => @company.id)

    else
      render('edit')
    end
  end

  def destroy
    @company = Company.find(params[:id]).destroy
    flash[:notice] = "Company '#{@company.name}' has been deleted"
    redirect_to(:controller => 'home', :action => 'index')

  end

  private

  def company_params
    params.require(:company).permit(:name, :image)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contacts = Contact.all
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)

    if @contact.save
      flash[:notice] = "Contact '#{@contact.full_name}' created Successfully"
      redirect_to(:controller => 'home', :action => 'index')

    else
      render('new')
    end
  end

  def edit
    @contact = Contact.find(params[:id])
  end

  def update
    @contact = Contact.find(params[:id])

    if @contact.update_attributes(contact_params)
      flash[:notice] = "Contact '#{@contact.full_name}' has been updated"
      redirect_to(:action => 'show', :id => @contact.id)

    else
      render('edit')
    end
  end

  def destroy
    @contact = Contact.find(params[:id]).destroy
    flash[:notice] = "Contact '#{@contact.full_name}' has been deleted"
    redirect_to(:controller => 'home', :action => 'index')

  end

  def show
    @contact = Contact.find(params[:id])
    @friendships = @contact.friendships_build
  end

  private

  def contact_params
    params.require(:contact).permit(:first_name, :last_name, :company_id, :position, :phone, :email, :image)
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def index
    @friendships = Friendship.all
  end

  def show
    @friendship = Friendship.find(params[:id])
  end

  def new
    @friendship = Friendship.new
  end

  def create
    @friendship = Friendship.new(friendship_params)

    if @friendship.save
      flash[:notice] = "Friendship created Successfully"
      redirect_to(:controller => 'home', :action => 'index')

    else
      render('new')
    end
  end

  def edit
    @friendship = Friendship.find(params[:id])
  end

  def update
    @friendship = Friendship.find(params[:id])

    if @friendship.update_attributes(friendship_params)
      flash[:notice] = "Friendship updated"
      redirect_to(:action => 'show', :id => @friendship.id)

    else
      render('edit')
    end
  end

  def destroy
    @friendship = Friendship.find(params[:id]).destroy
    flash[:notice] = "Friendship has been destroyed :("
    redirect_to(:controller => 'home', :action => 'index')

  end

  private

  def friendship_params
    params.require(:friendship).permit(:contact_id, :friend_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @companies = Company.all
    @contacts = Contact.all
    @friendships = Friendship.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def error_messages_for(object)
    render(:partial => 'application/error_messages', :locals => {:object => object})
  end

end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/application/_error_messages.html.haml
-if object && object.errors.size > 0
  #error-explanation
    %h3
      = pluralize(object.errors.size, 'error')
      prohibited this record from being saved
    %p problems with the following fields:
    %ul
      - object.errors.full_messages.each do |msg|
        %li= msg

app/views/companies/_company_list.html.haml
%table.table.table-striped
  - @companies.each do |c|
    %tr
      %td.company-list-item
        %span{:class => "glyphicon glyphicon-briefcase"}
        %strong=link_to c.name, company_path(c)
        -#%strong=link_to c.name, :controller => 'companies', :action => 'show', :id => c.id
        .edit-links
          %td=link_to 'Edit', :controller => 'companies', :action => 'edit', :id => c.id
          %td
            =link_to({:controller => 'companies', :action => 'destroy', :id => c.id}, method: :delete, data: { confirm: 'Are you certain you want to delete ' + c.name + '?' }) do
              %span{:class => 'glyphicon glyphicon-trash'}

app/views/companies/create.html.erb
<h1>Companies#create</h1>
<p>Find me in app/views/companies/create.html.erb</p>

app/views/companies/destroy.html.erb
<h1>Companies#destroy</h1>
<p>Find me in app/views/companies/destroy.html.erb</p>

app/views/companies/edit.html.haml
%h2 Edit Company
= simple_form_for @company, url: {action: "update"}, html: { class: 'form-horizontal'} do |f|
  .form-group= f.input :name, :label_html => {:class => 'col-sm-2 control-label'}
  .form-group= f.input :image, as: :file, :label_html => {:class => 'col-sm-2 control-label'}
  .col-sm-offset-2.col-sm-10
    .form-group= f.submit 'Update Company', :input_html => {:class => 'btn btn-default'}

= link_to '<< Back to index page', :controller => 'home', :action => 'index'

app/views/companies/index.html.haml
%h2 Companies

-if !flash[:notice].blank?
  .row
    .notice.alert.alert-success
      =flash[:notice]

= render 'companies/company_list'
= link_to '<< Back to index page', :controller => 'home', :action => 'index'

app/views/companies/new.html.haml
%h2 Add a Company

= error_messages_for(@company)

= simple_form_for @company, url: {action: "create"}, html: { class: 'form-horizontal'} do |f|
  .form-group= f.input :name, :label_html => {:class => 'col-sm-2 control-label'}
  .form-group= f.input :image, as: :file, :label_html => {:class => 'col-sm-2 control-label'}
  .col-sm-offset-2.col-sm-10
    .form-group= f.submit 'Create Company', :input_html => {:class => 'btn btn-default'}

= link_to '<< Back to index page', :controller => 'home', :action => 'index'

app/views/companies/show.html.haml
.profile-pic
  -if @company.image?
    = image_tag @company.image_url(:profile).to_s
  -else
    = image_tag "company-placeholder.png"

%h2= @company.name
=link_to 'Edit company', :action => 'edit', :id => @company.id, :class => 'button'
%br
=link_to 'Delete company', {:action => 'destroy', :id => @company.id}, method: :delete, data: { confirm: 'Are you certain you want to delete ' + @company.name + '?' }

-unless @contacts.blank?
  .row
    %h3
      Contacts who work at
      %em= @company.name

  = render 'contacts/contact_list'

.row
  = link_to '<< Back to index page', :controller => 'home', :action => 'index'

app/views/companies/update.html.erb
<h1>Companies#update</h1>
<p>Find me in app/views/companies/update.html.erb</p>

app/views/contacts/_contact_list.html.haml
%table.table.table-striped
  - @contacts.each do |c|
    %tr
      %td{:class => 'contact-list-item'}
        %span{:class => "glyphicon glyphicon-user"}
        %strong=link_to c.full_name, :controller => 'contacts', :action => 'show', :id => c.id
        .edit-links
          %td=link_to 'Edit', :controller => 'contacts', :action => 'edit', :id => c.id
          %td
            =link_to({:controller => 'contacts', :action => 'destroy', :id => c.id}, method: :delete, data: { confirm: 'Are you certain you want to delete ' + c.full_name + '?' }) do
              %span{:class => 'glyphicon glyphicon-trash'}

app/views/contacts/create.html.erb
<h1>Contacts#create</h1>
<p>Find me in app/views/contacts/create.html.erb</p>

app/views/contacts/destroy.html.erb
<h1>Contacts#destroy</h1>
<p>Find me in app/views/contacts/destroy.html.erb</p>

app/views/contacts/edit.html.haml
%h2 Edit Contact

= simple_form_for @contact, url: {action: "update"}, html: { class: 'form-horizontal'} do |f|
  .form-group= f.input :first_name, :label_html => {:class => 'col-sm-2 control-label'}
  .form-group= f.input :last_name, :label_html => {:class => 'col-sm-2 control-label'}
  .form-group= f.association :company, :label_html => {:class => 'col-sm-2 control-label'}
  .form-group= f.input :position, :label_html => {:class => 'col-sm-2 control-label'}
  .form-group= f.input :phone, :label_html => {:class => 'col-sm-2 control-label'}
  .form-group= f.input :email, :label_html => {:class => 'col-sm-2 control-label'}
  .form-group= f.input :image, as: :file, :label => "Profile Picture:", :label_html => {:class => 'col-sm-2 control-label'}
  .col-sm-offset-2.col-sm-10
    .form-group= f.submit 'Update Contact', :input_html => {:class => 'btn btn-default'}

= link_to '<< Back to index page', :controller => 'home', :action => 'index'

app/views/contacts/index.html.haml
%h2 Contacts

-if !flash[:notice].blank?
  .row
    .notice.alert.alert-success
      =flash[:notice]

= render 'contact_list'
= link_to '<< Back to index page', :controller => 'home', :action => 'index'

app/views/contacts/new.html.haml
%h2 Add a Contact

= error_messages_for(@contact)

= simple_form_for @contact, url: {action: "create"}, html: { class: 'form-horizontal'} do |f|
  .form-group= f.input :first_name, :label_html => {:class => 'col-sm-2 control-label'}
  .form-group= f.input :last_name, :label_html => {:class => 'col-sm-2 control-label'}
  .form-group= f.association :company, :label_html => {:class => 'col-sm-2 control-label'}
  .form-group= f.input :position, :label_html => {:class => 'col-sm-2 control-label'}
  .form-group= f.input :phone, :label_html => {:class => 'col-sm-2 control-label'}
  .form-group= f.input :email, :label_html => {:class => 'col-sm-2 control-label'}
  .form-group= f.input :image, as: :file, :label => "Profile Picture:", :label_html => {:class => 'col-sm-2 control-label'}
  .col-sm-offset-2.col-sm-10
    .form-group= f.submit 'Create Contact', :input_html => {:class => 'btn btn-default'}

= link_to '<< Back to index page', :controller => 'home', :action => 'index'

app/views/contacts/show.html.haml
// Full Name & Photo
.profile-pic
  -if @contact.image?
    = image_tag @contact.image_url(:profile).to_s
  -else
    = image_tag "profile-picture-placeholder.png"
%h2=@contact.full_name

//Position at Company
.contact-info
  %h3
    =@contact.position + ' at '
    =link_to @contact.company.name, :controller => "companies", :action => "show", :id => @contact.company.id
  =link_to 'Edit contact', :action => 'edit', :id => @contact.id, :class => 'button'
  %br
  =link_to 'Delete contact', {:action => 'destroy', :id => @contact.id}, method: :delete, data: { confirm: 'Are you certain you want to delete ' + @contact.full_name + '?' }

  // Contact Info
  %table.table.table-striped
    -if @contact.phone != ""
      %tr
        %td
          %span{:class => 'glyphicon glyphicon-earphone'}
          =@contact.phone

    -if @contact.email != ""
      %tr
        %td
          %span{:class => 'glyphicon glyphicon-envelope'}
          =mail_to @contact.email, @contact.email


//Friendships
%h3=@contact.first_name + ' is friends with:'
- @friendships.each do |f|

  -if f.contact != @contact
    %li
      - if f.contact.image?
        = image_tag f.contact.image_url(:thumb).to_s
      - else
        = image_tag "profile-picture-placeholder.png", :height => '50', :width => '50'
      =link_to f.contact.full_name, :controller => "contacts", :action => "show", :id => f.contact_id

  -if f.friend != @contact
    %li
      - if f.friend.image?
        = image_tag f.friend.image_url(:thumb).to_s
      - else
        = image_tag "profile-picture-placeholder.png", :height => '50', :width => '50'
      =link_to f.friend.full_name, :controller => "contacts", :action => "show", :id => f.friend_id

= link_to '<< Back to index page', :controller => 'home', :action => 'index'

app/views/contacts/update.html.erb
<h1>Contacts#update</h1>
<p>Find me in app/views/contacts/update.html.erb</p>

app/views/friendships/_friendship_list.html.haml
%table.table.table-striped
  -@friendships.each do |f|
    %tr
      %td{:class => 'friendship-list-item'}
        %span{:class => "glyphicon glyphicon-transfer"}
        %strong=link_to f.friendship_short_desc, :controller => 'friendships', :action => 'show', :id => f.id
        .edit-links
          %td=link_to 'Edit', :controller => 'friendships', :action => 'edit', :id => f.id
          %td
            =link_to({:controller => 'friendships', :action => 'destroy', :id => f.id}, method: :delete, data: { confirm: 'Are you certain you want to delete this friendship?' }) do
              %span{:class => 'glyphicon glyphicon-trash'}

app/views/friendships/create.html.erb
<h1>Friendships#create</h1>
<p>Find me in app/views/friendships/create.html.erb</p>

app/views/friendships/destroy.html.erb
<h1>Friendships#destroy</h1>
<p>Find me in app/views/friendships/destroy.html.erb</p>

app/views/friendships/edit.html.haml
%h2 Edit Friendship
= simple_form_for @friendship, url: {action: 'update'}, html: { class: 'form-horizontal'} do |f|
  .form-group= f.association :contact, label_method: :full_name, value_method: :id, include_blank: false, :label_html => {:class => 'col-sm-2 control-label'}
  .form-group= f.association :friend, label_method: :full_name, value_method: :id, include_blank: false, :label_html => {:class => 'col-sm-2 control-label'}
  .col-sm-offset-2.col-sm-10
    .form-group= f.submit 'Edit Friendship', :input_html => {:class => 'btn btn-default'}

= link_to '<< Back to index page', :controller => 'home', :action => 'index'

app/views/friendships/index.html.haml
%h2 Friendships

-if !flash[:notice].blank?
  .row
    .notice.alert.alert-success
      =flash[:notice]

= render 'friendship_list'
= link_to '<< Back to index page', :controller => 'home', :action => 'index'

app/views/friendships/new.html.haml
%h2 Add a Friendship

= error_messages_for(@friendship)

= simple_form_for @friendship, url: {action: 'create'}, html: { class: 'form-horizontal'} do |f|
  .form-group= f.association :contact, label_method: :full_name, value_method: :id, include_blank: false, :label_html => {:class => 'col-sm-2 control-label'}
  .form-group= f.association :friend, label_method: :full_name, value_method: :id, include_blank: false, :label_html => {:class => 'col-sm-2 control-label'}
  .col-sm-offset-2.col-sm-10
    .form-group= f.submit 'Create Friendship', :input_html => {:class => 'btn btn-default'}

= link_to '<< Back to index page', :controller => 'home', :action => 'index'

app/views/friendships/show.html.haml
.row
  .friendship-images
    - if @friendship.contact.image?
      = image_tag @friendship.contact.image_url(:profile).to_s
    - else
      = image_tag "profile-picture-placeholder.png"
    - if @friendship.friend.image?
      = image_tag @friendship.friend.image_url(:profile).to_s
    - else
      = image_tag "profile-picture-placeholder.png"
  %h2=@friendship.friendship_desc
  .friendship-links
    =link_to 'Edit Friendship', :action => 'edit', :id => @friendship.id, :class => 'button'
    %br
    =link_to 'Delete Friendship', {:action => 'destroy', :id => @friendship.id}, method: :delete, data: { confirm: 'Are you certain you want to delete this friendship?' }
.row
  = link_to '<< Back to index page', :controller => 'home', :action => 'index'

app/views/home/index.html.haml
.page-header
  %h1
    Companies & Contacts
    %small See who's who in the Zoo

-if !flash[:notice].blank?
  .row
    .notice.alert.alert-success
      =flash[:notice]

.row
  .col-lg-3.col-lg-offset-1.col-md-4.col-sm-4.col-xs-11
    .panel.panel-primary
      .panel-heading
        %h2.panel-title Companies
      .panel-body
        = render 'companies/company_list'
      .panel-footer
        = link_to "Add a Company", :controller => 'companies', :action => 'new'

  .col-lg-3.col-md-4.col-sm-4.col-xs-11
    .panel.panel-primary
      .panel-heading
        %h2.panel-title Contacts
      .panel-body
        = render 'contacts/contact_list'
      .panel-footer
        = link_to "Add a Contact", :controller => 'contacts', :action => 'new'

  .col-lg-3.col-md-4.col-sm-4.col-xs-11
    .panel.panel-primary
      .panel-heading
        %h2.panel-title Friendships
      .panel-body
        = render 'friendships/friendship_list'
      .panel-footer
        = link_to "Add a Friendship", :controller => 'friendships', :action => 'new'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Companies</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<%= yield %>

</body>
</html>